openapi: 3.0.3
info:
  title: OpenAPI schema for Cert-Manager template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where Cert-Manager will be installed.
          default: cert-manager
          x-walrus-ui:
            group: Basic
            order: 1
        helm_release_name:
          title: Helm Release Name
          type: string
          description: Name for the Cert-Manager Helm release.
          default: cert-manager
          x-walrus-ui:
            group: Basic
            order: 2
        helm_release_version:
          title: Helm Release Version
          type: string
          description: Version of the Cert-Manager Helm chart.
          default: 1.16.2
          x-walrus-ui:
            group: Basic
            order: 3
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for Harbor Helm release.
          default:
            cainjector:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
            cert_manager:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
            webhook:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
          additionalProperties:
            properties:
              limits:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Limits
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 1
              requests:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Requests
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 2
            required:
            - limits
            - requests
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        hpa_config:
          title: Hpa Config
          type: object
          description: Configuration for the HPA targeting All Cert-Manager Deployments
          default:
            max_replicas: 3
            min_replicas: 1
            target_cpu_utilization: 80
            target_memory_utilization: 80
          required:
          - max_replicas
          - min_replicas
          - target_cpu_utilization
          - target_memory_utilization
          properties:
            max_replicas:
              title: Max Replicas
              type: number
              x-walrus-ui:
                order: 2
            min_replicas:
              title: Min Replicas
              type: number
              x-walrus-ui:
                order: 1
            target_cpu_utilization:
              title: Target Cpu Utilization
              type: number
              x-walrus-ui:
                order: 3
            target_memory_utilization:
              title: Target Memory Utilization
              type: number
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
